# Based on https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

name: Build and push image to Docker Hub

#
# This Action builds images for new tags and pull requests
#  builds of tags are pushed to Docker Hub
#

on:
  pull_request: {}
  create: {}

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    # only build and push when this is a push of new tag or a PR
    if: ${{ startsWith( github.ref, 'refs/tags/') || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse Repo Name
        id: repo-name
        run: |
          echo "::set-output name=repo::${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=org::${GITHUB_REPOSITORY%/*}"
          printf "::group::Outputs:\nrepo: ${GITHUB_REPOSITORY#*/}\norg: ${GITHUB_REPOSITORY%/*}\n::endgroup::"

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # tag and push to <docker_username>/<repo_name>
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.repo }}
          tag-semver: |
            {{major}}.{{minor}}.{{patch}}
            {{major}}.{{minor}}
            {{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
